# fly.toml app configuration file generated for ragndrop on 2023-12-02T07:21:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ragndrop"
primary_region = "ord"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "ragndrop.fly.dev"
  PORT = "8080"

[[mounts]]
  source = "pdf"
  destination = "/pdf"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
